### ISSUE TITLE
rename GetWorlDataAsync to GetGlobalDataAsync

### ISSUE THREAD

**Issue by pujux** [egbakou/Covid19Tracker.NET#6]
- typo
- global data sounds more intuitive

**Comment by pujux** [comment]
oh i guess the typo was intended?

**Comment by egbakou** [comment]
Thanks for your contribution @puf17640 
I will rename it soon.

**Comment by pujux** [comment]
i can make a pr if you want

**Comment by egbakou** [comment]
Oooh Okay, you can.
So, waiting for your PR :)

**Comment by egbakou** [comment]
@all-contributors please add @puf17640 for code, test and doc
